# Generated by Django 6.1.2 on 2026-10-10 14:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(help_text="Entre o nome completo", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="E-mail institucional (@puc-rio.br)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        help_text="Número de matrícula na PUC-Rio",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "curso",
                    models.CharField(help_text="Curso de graduação", max_length=100),
                ),
                (
                    "membro_desde",
                    models.DateField(
                        help_text="Data de cadastro no UniRide",
                        verbose_name="Membro desde",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        help_text="Usuário do Django usado no login (pode ficar vazio)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aluno",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Alunos",
                "db_table": "Aluno",
                "ordering": ["nome"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Trajeto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("OFERECE", "Oferece carona"),
                            ("PROCURA", "Procura carona"),
                        ],
                        help_text="Oferece ou procura carona",
                        max_length=7,
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        help_text="Bairro de partida (ex.: Botafogo)", max_length=100
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        default="PUC-Rio", help_text="Destino da carona", max_length=100
                    ),
                ),
                (
                    "horario",
                    models.TimeField(
                        help_text="Horário de saída no formato HH:MM",
                        verbose_name="Horário de saída",
                    ),
                ),
                (
                    "vagas",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Vagas oferecidas no carro (1 a 4). Use 0 quando o aluno procura carona.",
                        validators=[django.core.validators.MaxValueValidator(4)],
                    ),
                ),
                ("dom", models.BooleanField(default=False, verbose_name="Domingo")),
                ("seg", models.BooleanField(default=False, verbose_name="Segunda")),
                ("ter", models.BooleanField(default=False, verbose_name="Terça")),
                ("qua", models.BooleanField(default=False, verbose_name="Quarta")),
                ("qui", models.BooleanField(default=False, verbose_name="Quinta")),
                ("sex", models.BooleanField(default=False, verbose_name="Sexta")),
                ("sab", models.BooleanField(default=False, verbose_name="Sábado")),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para esconder o trajeto da busca",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        help_text="Aluno dono do trajeto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajetos",
                        to="UniRide.aluno",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trajetos",
                "db_table": "Trajeto",
                "ordering": ["horario"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Aguardando confirmação"),
                            ("ACEITA", "Aceita"),
                            ("RECUSADA", "Recusada"),
                        ],
                        default="PENDENTE",
                        help_text="Situação do pedido",
                        max_length=8,
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do pedido"
                    ),
                ),
                (
                    "passageiro",
                    models.ForeignKey(
                        help_text="Aluno que pediu a carona",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="UniRide.aluno",
                    ),
                ),
                (
                    "trajeto",
                    models.ForeignKey(
                        help_text="Trajeto oferecido pelo motorista",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="UniRide.trajeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
                "db_table": "Solicitacao",
                "ordering": ["-data_criacao"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "placa",
                    models.CharField(
                        help_text="Placa no formato ABC1D23", max_length=8, unique=True
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Modelo do carro (ex.: Onix)", max_length=50
                    ),
                ),
                ("cor", models.CharField(help_text="Cor do carro", max_length=30)),
                (
                    "motorista",
                    models.OneToOneField(
                        help_text="Aluno proprietário do veículo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veiculo",
                        to="UniRide.aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "db_table": "Veiculo",
                "ordering": ["placa"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "estrelas",
                    models.PositiveSmallIntegerField(
                        help_text="Nota de 1 a 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comentario",
                    models.TextField(
                        blank=True,
                        help_text="Comentário opcional",
                        verbose_name="Comentário",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da avaliação"
                    ),
                ),
                (
                    "avaliado",
                    models.ForeignKey(
                        help_text="Aluno que recebeu a avaliação",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_recebidas",
                        to="UniRide.aluno",
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        help_text="Aluno que fez a avaliação",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_feitas",
                        to="UniRide.aluno",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        help_text="Carona (solicitação aceita) que está sendo avaliada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="UniRide.solicitacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "db_table": "Avaliacao",
                "ordering": ["-data"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("solicitacao", "avaliador"),
                        name="avaliacao_unica_por_carona",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.UniqueConstraint(
                fields=("trajeto", "passageiro"), name="solicitacao_unica_por_trajeto"
            ),
        ),
    ]
